NN: 
	clang++ -Wall -std=c++11 -O2 -g -o bin/NearestNeighbours.exe  NearestNeighbours.cpp -I "./include/armadillo" 
	./bin/NearestNeighbours.exe 

LR:
	clang++ -Wall -std=c++11 -O2 -g -o bin/LogisticRegression.exe  LogisticRegression.cpp -I "./include/armadillo" 
	./bin/LogisticRegression.exe 